name: MainWorkflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_PATH: ${{ github.workspace }}

jobs:
  WindowsBasedPlatformsBuild:
    name: ${{ matrix.targetPlatform }} build (${{ matrix.unityVersion }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - EmptyUnityGame
        unityVersion:
          - 2020.2.1f1
          - 2022.3.38f1
        targetPlatform:
          - Android # Build an Android player.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Print PROJECT_PATH
        run: echo $PROJECT_PATH
      - uses: actions/cache@v4
        with:
          path: $PROJECT_PATH/Library
          key:
            Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-
            Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ $PROJECT_PATH }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targetPlatform }}Build
          path: $PROJECT_PATH/build/${{ matrix.targetPlatform }}