name: MainWorkflow

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ "main" ]
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch: # to run manually

jobs:
  MultiplatformBuild:
    name: Deploy to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Event name
        run: echo Triggered by ${{ github.event_name }}
      - if: ${{ github.event_name }} == 'push'
        name: Print Git push event
        run: echo ${{ github.event.push }}
      - if: ${{ github.event_name }} == 'pull_request'
        name: Print Git pull request event
        run: echo ${{ github.event.pull_request }}
      - name: Print gh list
        run: echo $(gh run list)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}