name: MainWorkflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  MultiplatformPlatformBuild:
    name: ${{ matrix.targetPlatform }} build (${{ matrix.unityVersion }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2022.3.38f1
          - 6000.0.47f1
        targetPlatform:
          - Android # Build an Android player.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Set ProjectName variable
        run: echo PROJECT_NAME=${{ github.repository }} | awk -F'[\\\\/]' '{print $2}' >> $GITHUB_ENV
      - name: Print ProjectName
        run: echo ${{ env.PROJECT_NAME }}
      - uses: actions/cache@v4
        with:
          path: Library
          key:
            Library-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}-
            Library-${{ matrix.unityVersion }}
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - if: matrix.targetPlatform != 'Android'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}.${{ matrix.targetPlatform }}.${{ matrix.unityVersion }}.Build
          path: build/${{ matrix.targetPlatform }}
      - if: matrix.targetPlatform == 'Android'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}.${{ matrix.targetPlatform }}.${{ matrix.unityVersion }}
          path: build/${{ matrix.targetPlatform }}/Android.apk